DROP TABLE IF EXISTS db_encuesta;
CREATE DATABASE IF NOT EXISTS db_encuesta;
use db_encuesta;

CREATE TABLE user(
 dni varchar(20) not null,
 names varchar(100) not null,
 lastname varchar(100) not null,
 password text not null,
 created_at timestamp null default now(),
 primary key (dni)
);

INSERT INTO user(dni,names,lastname,password) values('Survey','User Test','Young Voice','survey2019');
select *from user;
CREATE TABLE surveys_questions (
q_id int NOT NULL auto_increment,
q_nro varchar(50) null,
disabled varchar(20) null,
q_description text default NULL,
q_created_at timestamp null default now(),
PRIMARY KEY  (q_id)
);


INSERT INTO surveys_questions(q_nro,q_description,disabled) VALUES ('Sexo:','','false'),
                          ('Edad:','','false'),
                                                    ('Vivo en:','','false'),
                                                    ('Pregunta 2:','¿En qué grado de estudios te encuentras?','false'),
                                                    ('Pregunta 3.a:','¿Has oído hablar sobre el documento de la Convención sobre los Derechos del Niño?','false'),
                                                    ('Pregunta 3.b:','¿Has oído hablar sobre los derechos de las niñas,niños y adolescentes?','false'),
                                                    ('Pregunta 4.a:','¿Durante este año escolar, te han expuesto en tu Centro Escolar la Convención sobre los Derechos del Niño?','false'),
                                                    ('Pregunta 4.b:','¿Durante este año escolar, te han expuesto en tu Centro Escolar los derechos de las niñas,niños y adolescentes?','false'),
                                                    ('Pregunta 5:','¿Crees que es importante que los políticos y los responsables de la toma de decisiones escuchen lo que las niñas, niños y adolescentes piensan sobre diferentes temas?','false'),
                                                    ('Pregunta 6:','¿Cuántas crees que son las oportunidades que tienes para presentar tus puntos de vista y opiniones a los responsables de la toma de decisiones en tu Municipalidad?','false'),
                                                    ('Pregunta 7.a:','¿Durante este año,has podido dar tu opinión o influir en alguna decisión que te afecte o sea importante para ti?','false'),
                                                    ('Pregunta 7.b:','¿Sobre que temas diste tu opinión?','true'),
                                                    ('Pregunta 7.c:','¿Dónde has podido dar tu opinión acerca de cualquier asunto importante para ti?','true'),
                                                    ('Pregunta 8.a:','¿Te gustaría tener mayor influencia, poder y oportunidades para influir / dar tu opinión sobre temas que te interesan y a otros niños,niñas y adolescentes?','false'),
                                                    ('Pregunta 8.b:','¿En qué temas te gustaría dar tu opinión?','true'),
                                                    ('Pregunta 9.a:','¿El Salvador necesita hacer más para detener el bullying (acoso escolar) y el ciberbullying?','false'),
                                                    ('Pregunta 9.b:','¿El Salvador debe hacer más para asegurarse que mujeres y varones accedan a las mismas oportunidades?','false'),
                                                    ('Pregunta 9.c:','¿El Salvador necesita hacer más para asegurarse que las niñas, niños y adolescentes ejerzan sus derechos?','false'),
                                                    ('Pregunta 9.d:','¿El Salvador debe hacer más para ayudar a las niñas, niños y adolescentes que intentan lastimarse a sí mismos?','false'),
                                                    ('Pregunta 9.e:','¿El Salvador debe hacer más para asegurarse de que existan más psicólogos que atiendan a las niñas,niños y adolescentes?','false'),
                                                    ('Pregunta 9.f:','¿El Salvador necesita hacer más para detener la discriminación de cualquier tipo?','false'),
                                                    ('Pregunta 9.g:','¿El Salvador necesita hacer más para ayudar a las niñas, niños y adolescentes que viven en pobreza?','false'),
                                                    ('Pregunta 9.h:','¿El Salvador debe hacer más para mejorar la situación de las niñas, niños y adolescentes con discapacidad?','false'),
                                                    ('Pregunta 9.i:','¿El Salvador necesita hacer más para asegurar que hayan Espacios de participación de Niñas, Niños y Adolescentes en tu comunidad y Centro Educativo?','false'),
                                                    ('Pregunta 9.j:','¿El Salvador necesita hacer más para luchar contra la violencia?','false'),
                                                    ('Pregunta 9.k:','¿El Salvador necesita hacer más para reducir el embarazo adolescentes?','false'),
                                                    ('Pregunta 9.l:','¿El Salvador necesita hacer más para las niñas, niños y adolescentes, no caigan en la delincuencia?','false'),
                                                    ('Pregunta 9.m:','¿El Salvador necesita hacer más para las niñas, niños y adolescentes, no caigan en las drogas?','false'),
                                                    ('Pregunta 9.n:','¿El Salvador necesita hacer más para combatir el cambio climático y problemas ambientales?','false'),
                                                    ('Pregunta 10.1:','¿Tienes acceso a internet en tu casa?','false'),
                                                    ('Pregunta 10.2:','¿Tienes acceso a una computadora en tu casa?','false'),
                                                    ('Pregunta 10.3:','¿Tienes tu propia habitación en casa?','false'),
                                                    ('Pregunta 11.a:','¿Tienes tu propio teléfono celular?','false'),
                                                    ('Pregunta 11.b:','¿Tu teléfono celular tiene internet?','true'),
                                                    ('Pregunta 12:','¿En el Centro Escolar se te enseñó cómo usar Internet de manera segura?','false'),
                                                    ('Pregunta 13.a:','¿Has dejado de participar en alguna actividad escolar porque ha costado dinero?','false'),
                                                    ('Pregunta 13.b:','¿Has dejado de participar en alguna actividad recreativa porque no podías pagar los insumos o materiales que debías llevar?','false'),
                                                    ('Pregunta 14.a:','¿Has dejado de ir a la escuela debido a riesgos ambientales como inundaciones, deslizamientos o mala calidad del aire?','false'),
                                                    ('Pregunta 14.b:','¿Has dejado de disfrutar de alguna actividad recreativa al aire libre debido a riesgos ambientales como inundaciones, deslizamientos, basura, mala calidad del aire?','false'),
                                                    ('Pregunta 15:','¿Comprendes las tareas que te dejan tus profesores?','false'),
                                                    ('Pregunta 16:','¿Recibes ayuda en casa con las tareas de la escuela?','false'),
                                                    ('Pregunta 17:','¿Recibes ayuda en la escuela para realizar tus tareas?','false'),
                                                    ('Pregunta 18:','¿Estás satisfecho/a con la enseñanza que recibes en tu Centro Escolar?','false'),
                                                    ('Pregunta 19.a:','¿Sientes que los maestros y otro personal de tu Centro Escolar trabajan para detener el acoso escolar o bullying?','false'),
                                                    ('Pregunta 19.b:','¿Sientes que las y los maestros y otro personal de tu Centro Escolar trabajan para prevenir el embarazo adolescente?','false'),
                                                    ('Pregunta 19.c:','¿Sientes que las y los maestros y otro personal de tu Centro Escolar trabajan para que las niñas, niños y adolescentes no integren una mara o pandilla,o caigan ensurveys_options la delincuencia o la violencia?','false'),
                                                    ('Pregunta 20:','¿Crees que tu Centro Escolar hace lo suficiente para brindar apoyo especial a las niñas,niños y adolescentes con discapacidad?','false'),
                                                    ('Pregunta 21:','En tu Centro Escolar, ¿hay oportunidad para que presentes tus opiniones sobre temas relacionadas con la escuela?','false'),
                                                    ('Pregunta 22.a:','¿Te sientes seguro(a) en tu camino hacia y desde el Centro Escolar o Instituto?','false'),
                                                    ('Pregunta 22.b:','¿Te sientes seguro(a) en tu aula?','false'),
                                                    ('Pregunta 22.c:','¿Te sientes seguro(a) durante los recreos?','false'),
                                                    ('Pregunta 22.d:','¿Te sientes seguro(a) en el municipio/comunidad en donde vives?','false'),
                                                    ('Pregunta 22.e:','¿Te sientes seguro(a) en los lugares en los que realizas actividades deportivas, artísticas,culturales,etc.?','false'),
                                                    ('Pregunta 22.f:','¿Te sientes seguro(a) en el centro de tu municipio/comunidad durante el día?','false'),
                                                    ('Pregunta 22.g:','¿Te sientes seguro(a) en el centro de tu municipio/comunidad por la noche?','false'),
                                                    ('Pregunta 22.h:','¿Te sientes seguro(a) en el autobús, movilidad escolar, durante el día?','false'),
                                                    ('Pregunta 22.i:','¿Te sientes seguro(a) en el autobús, movilidad escolar, durante la noche?','false'),
                                                    ('Pregunta 22.j:','¿Te sientes seguro(a) en casa?','false'),
                                                    ('Pregunta 22.k:','¿Te sientes seguro(a) estando conectado a Internet?','false'),
                                                    ('Pregunta 23:','Durante este año has estado preocupado(a) o ansioso(a) acerca de cualquiera de las siguientes cosas:','false'),
                                                    ('Pregunta 24:','¿Durante este año, te ha sucedido esto?','false'),
                                                    ('Pregunta 25.1:','¿Te sientes estresado(a) con las labores escolares?','false'),
                                                    ('Pregunta 25.2:','¿Te sientes estresado(a) debido a tus calificaciones?','false'),
                                                    ('Pregunta 25.3:','¿Te sientes triste por un período de tiempo largo?','false'),
                                                    ('Pregunta 25.4:','¿Te has sentido acosado (víctima de bullying) durante el año escolar?','false'),
                                                    ('Pregunta 25.a:','Sí te has sentido acosado (víctima de bullying) durante el año debido a:','true'),
                                                    ('Pregunta 26:','¿Sabes a dónde acudir cuando necesites hablar con alguien o pedir ayuda:','false'),
                                                    ('Pregunta 27:','¿Cómo ves tu futuro?','false'),
                          ('Pregunta 28.1:','¿Cómo ves el futuro de nuestro planeta?','false'),
                                                    ('Pregunta 28.2:','¿Crees que tu vida futura será diferente a la de sus padres debido al cambio climático?','false'),
                                                    ('Pregunta 29:','¿Crees que podrás obtener un trabajo cuando salgas de la escuela?','false');
select *from surveys_questions;
CREATE TABLE surveys_options (
o_id int NOT NULL auto_increment,
q_id int NOT NULL,
o_description text default NULL,
o_active varchar(20) null,
o_created_at timestamp null default now(),
PRIMARY KEY  (o_id),
foreign key(q_id) references surveys_questions(q_id)
);


INSERT INTO surveys_options(q_id,o_description,o_active) VALUES(1,'Femenino','false'),
                            (1,'Maculino','false'),
                                                      (2,'12 años','false'),
                                                      (2,'13 años','false'),
                                                      (2,'14 años','false'),
                                                      (2,'15 años','false'),
                                                      (2,'16 años','false'),
                                                      (2,'17 años ','false'),
                                                      (3,'Zona rural','false'),
                                                      (3,'Zona urbana','false'),
                                                      (4,'Quinto grado de básica','false'),
                                                      (4,'Sexto grado de básica','false'),
                                                      (4,'Séptimo grado de básica','false'),
                                                      (4,'Octavo grado de básica','false'),
                                                      (4,'Noveno grado de básica','false'),
                                                      (4,'Primero de Bachillerato','false'),
                                                      (4,'Segundo de Bachillerato','false'),
                                                      (4,'Concluyó','false'),
                                                      (4,'No estudia','false'),
                                                      (5,'Sí','false'),
                                                      (5,'No','false'),
                                                      (6,'Sí','false'),
                                                      (6,'No','false'),
                                                      (7,'Sí','false'),
                                                      (7,'No','false'),
                                                      (7,'No Recuerdo','false'),
                                                      (8,'Sí','false'),
                                                      (8,'No','false'),
                                                      (8,'No Recuerdo','false'),
                                                      (9,'Sí','false'),
                                                      (9,'No','false'),
                                                      (10,'Muchas oportunidades','false'),
                                                      (10,'Pocas oportunidades','false'),
                                                      (10,'No existen oportunidades','false'),
                                                      (10,'No lo sé','false'),
                                                      (10,'No es de mi interés','false'),
                                                      (11,'Sí','false'),
                                                      (11,'No','false'),
                                                      (12,'Educación','false'),
                                                      (12,'Violencia','false'),
                                                      (12,'Participación','false'),
                                                      (12,'Discriminación','false'),
                                                      (12,'Igualdad de derechos entre mujeres y varones','false'),
                                                      (12,'Problemas ambientales y cambio climático','false'),
                                                      (12,'Preparación ante emergencias','false'),
                                                      (12,'Sexualidad','false'),
                                                      (12,'Otro tema','true'),
                                                      (13,'En el Centro Escolar','false'),
                                                      (13,'En mi municipalidad','false'),
                                                      (13,'En casa','false'),
                                                      (13,'En alguna organización o agrupación','false'),
                                                      (13,'En actividades de tiempo libre','false'),
                                                      (14,'Sí','false'),
                                                      (14,'No','false'),
                                                      (15,'Educación','false'),
                                                      (15,'Violencia','false'),
                                                      (15,'Participación','false'),
                                                      (15,'Discriminación','false'),
                                                      (15,'Igualdad de derechos entre mujeres y varones','false'),
                                                      (15,'Problemas ambientales y cambio climático','false'),
                                                      (15,'Preparación ante emergencias','false'),
                                                      (15,'Sexualidad','false'),
                                                      (15,'Otro tema','true'),
                                                      (16,'Es muy necesario','false'),
                                                      (16,'Necesario','false'),
                                                      (16,'Poco necesario','false'),
                                                      (16,'No es necesario','false'),
                                                      (16,'No es de mi interés','false'),
                                                      (17,'Es muy necesario','false'),
                                                      (17,'Necesario','false'),
                                                      (17,'Poco necesario','false'),
                                                      (17,'No es necesario','false'),
                                                      (17,'No es de mi interés','false'),
                                                      (18,'Es muy necesario','false'),
                                                      (18,'Necesario','false'),
                                                      (18,'Poco necesario','false'),
                                                      (18,'No es necesario','false'),
                                                      (18,'No es de mi interés','false'),
                                                      (19,'Es muy necesario','false'),
                                                      (19,'Necesario','false'),
                                                      (19,'Poco necesario','false'),
                                                      (19,'No es necesario','false'),
                                                      (19,'No es de mi interés','false'),
                                                      (20,'Es muy necesario','false'),
                                                      (20,'Necesario','false'),
                                                      (20,'Poco necesario','false'),
                                                      (20,'No es necesario','false'),
                                                      (20,'No es de mi interés','false'),
                                                      (21,'Es muy necesario','false'),
                                                      (21,'Necesario','false'),
                                                      (21,'Poco necesario','false'),
                                                      (21,'No es necesario','false'),
                                                      (21,'No es de mi interés','false'),
                                                      (22,'Es muy necesario','false'),
                                                      (22,'Necesario','false'),
                                                      (22,'Poco necesario','false'),
                                                      (22,'No es necesario','false'),
                                                      (22,'No es de mi interés','false'),
                                                      (23,'Es muy necesario','false'),
                                                      (23,'Necesario','false'),
                                                      (23,'Poco necesario','false'),
                                                      (23,'No es necesario','false'),
                                                      (23,'No es de mi interés','false'),
                                                      (24,'Es muy necesario','false'),
                                                      (24,'Necesario','false'),
                                                      (24,'Poco necesario','false'),
                                                      (24,'No es necesario','false'),
                                                      (24,'No es de mi interés','false'),
                                                      (25,'Es muy necesario','false'),
                                                      (25,'Necesario','false'),
                                                      (25,'Poco necesario','false'),
                                                      (25,'No es necesario','false'),
                                                      (25,'No es de mi interés','false'),
                                                      (26,'Es muy necesario','false'),
                                                      (26,'Necesario','false'),
                                                      (26,'Poco necesario','false'),
                                                      (26,'No es necesario','false'),
                                                      (26,'No es de mi interés','false'),
                                                      (27,'Es muy necesario','false'),
                                                      (27,'Necesario','false'),
                                                      (27,'Poco necesario','false'),
                                                      (27,'No es necesario','false'),
                                                      (27,'No es de mi interés','false'),
                                                      (28,'Es muy necesario','false'),
                                                      (28,'Necesario','false'),
                                                      (28,'Poco necesario','false'),
                                                      (28,'No es necesario','false'),
                                                      (28,'No es de mi interés','false'),
                                                      (29,'Es muy necesario','false'),
                                                      (29,'Necesario','false'),
                                                      (29,'Poco necesario','false'),
                                                      (29,'No es necesario','false'),
                                                      (29,'No es de mi interés','false'),
                                                      (30,'Todo el tiempo','false'),
                                                      (30,'A veces','false'),
                                                      (30,'No tengo','false'),
                                                      (31,'Todo el tiempo','false'),
                                                      (31,'A veces','false'),
                                                      (31,'No tengo','false'),
                                                      (32,'Sí','false'),
                                                      (32,'No','false'),
                                                      (33,'Sí','false'),
                                                      (33,'No','false'),
                                                      (34,'Sí','false'),
                                                      (34,'No','false'),
                                                      (35,'Sí','false'),
                                                      (35,'No','false'),
                                                      (36,'Sí, siempre','false'),
                                                      (36,'Casi siempre','false'),
                                                      (36,'A veces','false'),
                                                      (36,'Nunca','false'),
                                                      (37,'Sí, siempre','false'),
                                                      (37,'Casi siempre','false'),
                                                      (37,'A veces','false'),
                                                      (37,'Nunca','false'),
                                                      (38,'Sí, siempre','false'),
                                                      (38,'Casi siempre','false'),
                                                      (38,'A veces','false'),
                                                      (38,'Nunca','false'),
                                                      (39,'Sí, siempre','false'),
                                                      (39,'Casi siempre','false'),
                                                      (39,'A veces','false'),
                                                      (39,'Nunca','false'),
                                                      (40,'Sí, siempre','false'),
                                                      (40,'Casi siempre','false'),
                                                      (40,'A veces','false'),
                                                      (40,'Nunca','false'),
                                                      (41,'Sí, siempre','false'),
                                                      (41,'Casi siempre','false'),
                                                      (41,'A veces','false'),
                                                      (41,'Nunca','false'),
                                                      (42,'Sí, siempre','false'),
                                                      (42,'Casi siempre','false'),
                                                      (42,'A veces','false'),
                                                      (42,'Nunca','false'),
                                                      (43,'Sí, siempre','false'),
                                                      (43,'Casi siempre','false'),
                                                      (43,'A veces','false'),
                                                      (43,'Nunca','false'),
                                                      (44,'Sí','false'),
                                                      (44,'No','false'),
                                                      (45,'Sí','false'),
                                                      (45,'No','false'),
                                                      (46,'Sí','false'),
                                                      (46,'No','false'),
                                                      (47,'Sí, siempre','false'),
                                                      (47,'Casi siempre','false'),
                                                      (47,'A veces','false'),
                                                      (47,'Nunca','false'),
                                                      (48,'Sí','false'),
                                                      (48,'No','false'),
                                                      (48,'No lo sé','false'),
                                                      (49,'Sí, siempre','false'),
                                                      (49,'Casi siempre','false'),
                                                      (49,'A veces','false'),
                                                      (49,'Nunca','false'),
                                                      (50,'Sí, siempre','false'),
                                                      (50,'Casi siempre','false'),
                                                      (50,'A veces','false'),
                                                      (50,'Nunca','false'),
                                                      (51,'Sí, siempre','false'),
                                                      (51,'Casi siempre','false'),
                                                      (51,'A veces','false'),
                                                      (51,'Nunca','false'),
                                                      (52,'Sí, siempre','false'),
                                                      (52,'Casi siempre','false'),
                                                      (52,'A veces','false'),
                                                      (52,'Nunca','false'),
                                                      (53,'Sí, siempre','false'),
                                                      (53,'Casi siempre','false'),
                                                      (53,'A veces','false'),
                                                      (53,'Nunca','false'),
                                                      (53,'No realizo otras actividades','false'),
                                                      (54,'Sí, siempre','false'),
                                                      (54,'Casi siempre','false'),
                                                      (54,'A veces','false'),
                                                      (54,'Nunca','false'),
                                                      (55,'Sí, siempre','false'),
                                                      (55,'Casi siempre','false'),
                                                      (55,'A veces','false'),
                                                      (55,'Nunca','false'),
                                                      (56,'Sí, siempre','false'),
                                                      (56,'Casi siempre','false'),
                                                      (56,'A veces','false'),
                                                      (56,'Nunca','false'),
                                                      (57,'Sí, siempre','false'),
                                                      (57,'Casi siempre','false'),
                                                      (57,'A veces','false'),
                                                      (57,'Nunca','false'),
                                                      (58,'Sí, siempre','false'),
                                                      (58,'Casi siempre','false'),
                                                      (58,'A veces','false'),
                                                      (58,'Nunca','false'),
                                                      (59,'Sí, siempre','false'),
                                                      (59,'Casi siempre','false'),
                                                      (59,'A veces','false'),
                                                      (59,'Nunca','false'),
                                                      (60,'No poder cumplir con las tareas de la escuela','false'),
                                                      (60,'Haber sido discriminado(a)','false'),
                                                      (60,'Haber sido víctima de bullying acosado(a)','false'),
                                                      (60,'Experimentar violencia de parte de otros niños, niñas o adolescentes','false'),
                                                      (60,'Experimentar violencia de parte de un adulto','false'),
                                                      (60,'Sobre la posibilidad de abandonar la escuela y no terminar los estudios','false'),
                                                      (60,'Que no recibas suficiente ayuda en la escuela','false'),
                                                      (60,'Que la familia no tenga suficiente dinero para cubrir los gastos necesario','false'),
                                                      (60,'Que te presionen para hacer algo que le resulte incomodo (sexo,alcohol y drogas)','false'),
                                                      (60,'Estar embarazada o tu pareja','false'),
                                                      (60,'Que el cambio climático o la degradación ambiental afecte tu entorno local y tu vida cotidiana.','false'),
                                                      (60,'Que los adultos no están haciendo lo suficiente sobre el cambio climático y los problemas ambientales.','false'),
                                                      (61,'Has sido obligado(a) o invitado(a) a formar parte de una pandilla o mara','false'),
                                                      (61,'No denuncie un acto de maltrato físico contra un niño(a) o adolescente del que tenía conocimiento','false'),
                                                      (61,'Has huido de casa o has sido expulsado de casa','false'),
                                                      (61,'Has recibido mensajes insultantes en línea de otros niños,niñas o adolescentes','false'),
                                                      (61,'Has recibido mensajes insultantes de otros niños, niñas o adolescentes en tu teléfono celular','false'),
                                                      (61,'Que un adulto se haya contactado en línea y haya querido hablar de sexo','false'),
                                                      (61,'Te han propuesto hacer algo ilícito','false'),
                                                      (61,'Has pensado o intentado quitarte la vida','false'),
                                                      (61,'No puedes estudiar como quisieras porque tienes que trabajar','false'),
                                                      (61,'He dejado de disfrutar de alguna actividad recreativa a causa de la violencia o los peligros en mi comunidad','false'),
                                                      (61,'No denuncie un acto de acoso o abuso sexual contra un niño(a) o adolescente del que tenía conocimiento','false'),
                                                      (62,'Sí, siempre','false'),
                                                      (62,'Casi siempre','false'),
                                                      (62,'A veces','false'),
                                                      (62,'Nunca','false'),
                                                      (63,'Sí, siempre','false'),
                                                      (63,'Casi siempre','false'),
                                                      (63,'A veces','false'),
                                                      (63,'Nunca','false'),
                                                      (64,'Sí, siempre','false'),
                                                      (64,'Casi siempre','false'),
                                                      (64,'A veces','false'),
                                                      (64,'Nunca','false'),
                                                      (65,'Sí','false'),
                                                      (65,'No','false'),
                                                      (65,'A veces','false'),
                                                      (66,'Tu fe / religión?','false'),
                                                      (66,'Tu situación económica','false'),
                                                      (66,'Qué tu familia está pasando por algún problema?','false'),
                                                      (66,'Que tus padres no viven contigo?','false'),
                                                      (66,'Alguna discapacidad?','false'),
                                                      (66,'Tu orientación sexual?','false'),
                                                      (66,'Tu apariencia?','false'),
                                                      (66,'Tu edad?','false'),
                                                      (66,'Otro motivo?','true'),
                                                      (67,'Sí te sientes mal mentalmente (muy ansioso(a),deprimido(a),triste,etc.)?','false'),
                                                      (67,'Sí tienes problemas en tu familia?','false'),
                                                      (67,'Sí tu o alguien que conoces ha estado expuesto a violencia,amenazas u otros peligros?','false'),
                                                      (67,'Sí te sientes hostigado(a) y tratado injustamente?','false'),
                                                      (67,'Sí tienes algún problemas con drogas y alcohol?','false'),
                                                      (67,'Sí tienes dudas sobre sexualidad?','false'),
                                                      (67,'Sí estas embarazada o tu pareja?','false'),
                                                      (67,'Sí tienes alguna habilidad o talento especial?','false'),
                                                      (67,'Sobre lo que te enseñan o los deberes de la escuela?','false'),
                                                      (68,'Muy positivamente','false'),
                                                      (68,'Positivamente','false'),
                                                      (68,'Negativamente','false'),
                                                      (68,'Muy negativamente','false'),
                                                      (68,'No lo sé','false'),
                                                      (68,'Prefiero no pensar en ello','false'),
                                                      (69,'Muy positivamente','false'),
                                                      (69,'Positivamente','false'),
                                                      (69,'Negativamente','false'),
                                                      (69,'Muy negativamente','false'),
                                                      (69,'No lo sé','false'),
                                                      (69,'Prefiero no pensar en ello','false'),
                                                      (70,'Si','false'),
                                                      (70,'No','false'),
                                                      (70,'No lo sé','false'),
                                                      (70,'Prefiero no pensar en ello','false'),
                                                      (71,'Sí','false'),
                                                      (71,'No','false'),
                                                      (71,'Tal vez','false'),
                                                      (71,'No lo sé','false');
                                                     
select *from surveys_options;

CREATE TABLE region(
r_id int not null auto_increment,
r_description text null,
r_created_at timestamp null default now(),
PRIMARY KEY  (r_id)
);

INSERT INTO region(r_description) values('Occidental'),('Oriental'),('Central'),('Paracentral');
select *from region;

CREATE TABLE departament(
d_id int not null auto_increment,
d_description text null,
r_id int not null,
PRIMARY KEY  (d_id),
d_created_at timestamp null default now(),
foreign key(r_id) references region(r_id)
);

INSERT INTO departament(d_description,r_id) VALUES('Ahuachapán',1),
                          ('Santa Ana',1),
                                                  ('Sonsonate',1),
                                                  ('Usulután',2),
                                                  ('San Miguel',2),
                                                  ('Morazán',2),
                                                  ('La Unión',2),
                                                  ('La Libertad',3),
                                                  ('Chalatenango',3),
                                                  ('Cuscatlán',3),
                                                  ('San Salvador',3),
                                                  ('La Paz',4),
                                                  ('Cabañas',4),
                                                  ('San Vicente',4);
SELECT *FROM departament;


SELECT *FROM departament;

CREATE TABLE surveys_answers (
a_id int NOT NULL auto_increment,
o_id int NOT NULL,
d_id int not null,
a_description text null,
dni varchar(20) not null,
a_created_at timestamp null default now(),
PRIMARY KEY  (a_id),
foreign key(o_id) references surveys_options(o_id),
foreign key(d_id) references departament(d_id),
foreign key(dni) references user(dni)
)

select *from surveys_answers

